name: Testing taskiq-pipelines

on: pull_request

jobs:
  lint:
    strategy:
      matrix:
        cmd: [ "black", "ruff-check", "mypy" ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
          fetch-depth: 0
      - id: setup-uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-suffix: 3.14
          version: "latest"
          python-version: 3.14
      - name: Install deps
        run: uv sync --frozen --all-extras
      - name: Run lint check
        run: uv run pre-commit run -a ${{ matrix.cmd }}
  pytest:
    strategy:
      matrix:
        py_version: [ "3.10", "3.11", "3.12", "3.13", "3.14" ]
        pydantic_ver: [ "<2", ">=2.5,<3" ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: "${{ matrix.os }}"
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
          fetch-depth: 0
      - id: setup-uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-suffix: ${{ matrix.py_version }}
          version: "latest"
          python-version: ${{ matrix.py_version }}
      - name: Install deps
        run: uv sync --frozen --all-extras
      - name: Setup pydantic version
        run: uv pip install "pydantic ${{ matrix.pydantic_ver }}"
      - name: Run pytest check
        run: uv run pytest -vv -n auto .
